{{- if .Values.bundle.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: penpot
  namespace: penpot
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Penpot
    gethomepage.dev/group: Design
spec:
  ingressClassName: {{ .Values.bundle.ingress.className | quote }}
  rules:
    - host: {{ .Values.bundle.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: penpot
                port:
                  number: 8080
{{- end }}
