apiVersion: v1
data:
  policy.csv: |
    p, role:admin, applications, *, */*, allow
    p, role:admin, projects, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, accounts, *, *, allow
    p, role:admin, log, *, */*, allow
    p, role:admin, exec, *, */*, allow
    g, argocd-admin, role:admin
  policy.default: ""
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"policy.csv":"p, role:admin, applications, *, */*, allow\np, role:admin, projects, *, *, allow\np, role:admin, repositories, *, *, allow\np, role:admin, clusters, *, *, allow\np, role:admin, accounts, *, *, allow\np, role:admin, log, *, */*, allow\np, role:admin, exec, *, */*, allow\ng, group:argocd-admin, role:admin\n","policy.default":""},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-rbac-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-rbac-cm","namespace":"argocd"}}
  creationTimestamp: "2025-12-30T14:54:01Z"
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "190672"
  uid: e3bd5e04-b26e-4376-b9f7-14e5cfeb89c6
