apiVersion: v1
kind: Secret
metadata:
  name: inventory-postgres-secret
  namespace: inventory
type: Opaque
stringData:
  POSTGRES_DB: inventory
  POSTGRES_USER: inventory
  POSTGRES_PASSWORD: inventory
