apiVersion: v1
kind: Service
metadata:
  name: inventory-web
  namespace: inventory
  labels:
    app: inventory-web
spec:
  type: NodePort
  selector:
    app: inventory-web
  ports:
    - port: 80
      targetPort: http
      nodePort: 30990
