apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - namespace.yaml
  - postgres-configmap.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - keycloak-service.yaml
  - keycloak-statefulset.yaml
