apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: Home
    theme: dark
    providers:
      - kubernetes: {}
  kubernetes.yaml: |
    mode: cluster
    ingress:
      enabled: true
    service:
      enabled: true
  services.yaml: |
    []
  bookmarks.yaml: |
    []
  widgets.yaml: |
    []
  docker.yaml: |
    {}
  custom.css: |
    /* empty */
  custom.js: |
    /* empty */
