apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: Home
    theme: dark
    providers:
      - kubernetes: {}
  kubernetes.yaml: |
    mode: cluster
    ingress:
      enabled: true
  services.yaml: |
    []
  bookmarks.yaml: |
    []
  widgets.yaml: |
    []
