apiVersion: v1
kind: Service
metadata:
  name: grocy
  namespace: grocy
  labels:
    app: grocy
    exposed: npm
spec:
  type: NodePort
  selector:
    app: grocy
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30880
