apiVersion: v1
kind: Service
metadata:
  name: librespeed
  namespace: speedtest
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: LibreSpeed
    gethomepage.dev/group: Utilities
spec:
  type: ClusterIP
  selector:
    app: librespeed
  ports:
    - name: http
      port: 80
      targetPort: 80
