apiVersion: v1
kind: Service
metadata:
  name: xorg-vnc
  namespace: android-emulators
  labels:
    app: xorg-gpu
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Xorg VNC
    gethomepage.dev/group: Android
spec:
  type: ClusterIP
  selector:
    app: xorg-gpu
  ports:
    - name: vnc
      port: 5900
      targetPort: 5900
