apiVersion: apps/v1
kind: Deployment
metadata:
  name: biblioteca-secreta-web
  namespace: media
  labels:
    app: biblioteca-secreta-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: biblioteca-secreta-web
  template:
    metadata:
      labels:
        app: biblioteca-secreta-web
    spec:
      nodeSelector:
        media-node: "true"
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: biblioteca-data
              mountPath: /data
              readOnly: true
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
      volumes:
        - name: biblioteca-data
          persistentVolumeClaim:
            claimName: biblioteca-secreta-nfs
        - name: nginx-conf
          configMap:
            name: nginx-biblioteca-secreta-conf