apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - namespace.yaml
  - pvc.yaml
  - pv-pvc-downloads-nfs.yaml
  - deployment-qbittorrent.yaml
  - deployment-prowlarr.yaml
  - deployment-lazylibrarian.yaml
  - service-qbittorrent.yaml
  - service-prowlarr.yaml
  - service-lazylibrarian.yaml
  - ingress.yaml
