apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment-qbittorrent.yaml
  - deployment-prowlarr.yaml
  - deployment-readarr.yaml
  - service-qbittorrent.yaml
  - service-prowlarr.yaml
  - service-readarr.yaml
  - ingress.yaml
