apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - namespace.yaml
  - pvc.yaml
  - pv-pvc-downloads-nfs.yaml
  - pv-pvc-books-nfs.yaml
  - pv-pvc-biblioteca-secreta-nfs.yaml
  - configmap-nginx-biblioteca.yaml
  - deployment-qbittorrent.yaml
  - deployment-prowlarr.yaml
  - deployment-lazylibrarian.yaml
  - deployment-biblioteca-secreta-web.yaml
  - service-qbittorrent.yaml
  - service-prowlarr.yaml
  - service-lazylibrarian.yaml
  - service-biblioteca-secreta-web.yaml
   - ingress.yaml
   # Meilisearch
   - pvc-meili.yaml
  - deployment-meili.yaml
  - service-meili.yaml
  # Job Indexer
  - job-biblioteca-indexer.yaml
   # Books Bot
   - configmap-books-bot.yaml
   - configmap-books-bot-code.yaml
   - deployment-books-bot.yaml
   - service-books-bot.yaml
