apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: android-emulators
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Android Redis
    gethomepage.dev/group: Android
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
