apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma
  namespace: monitoring-lite
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Uptime Kuma
    gethomepage.dev/group: Monitoring
spec:
  ingressClassName: nginx
  rules:
    - host: kuma.finalq.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma
                port:
                  number: 3001
