apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pantry-ingress
  namespace: pantry
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: pantry.finalq.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pantry-web
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: pantry-api
                port:
                  number: 80
