apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pantry
resources:
  - namespace.yaml
  - postgres-secret.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - api-secret.yaml
  - api-deployment.yaml
  - api-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - ingress.yaml
