apiVersion: v1
kind: Service
metadata:
  name: pantry-web
  namespace: pantry
  labels:
    app: pantry-web
spec:
  type: NodePort
  selector:
    app: pantry-web
  ports:
    - port: 80
      targetPort: http
      nodePort: 30991
