apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ha-dash-frontend
  namespace: ha-dash
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: HA Dash
    gethomepage.dev/group: Dashboards
spec:
  ingressClassName: nginx
  rules:
    - host: ha-dash.finalq.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ha-dash-frontend
                port:
                  number: 80
