apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  # secret.yaml y configmap.yaml se crean externamente, no est√°n en el repo
  - pvc.yaml
  - deployment-backend.yaml
  - deployment-frontend.yaml
  - service-backend.yaml
  - service-frontend.yaml
  - ingress.yaml
