apiVersion: v1
kind: Service
metadata:
  name: ha-dash
  namespace: ha-dash
  labels:
    app: ha-dash
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: HA Dash
    gethomepage.dev/group: Dashboards
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: ha-dash
