apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-torznab-indexer
  namespace: media
  labels:
    app: internal-torznab-indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internal-torznab-indexer
  template:
    metadata:
      labels:
        app: internal-torznab-indexer
    spec:
      containers:
        - name: internal-torznab-indexer
          image: harbor.finalq.xyz/tools/internal-torznab-indexer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: DATA_DIR
              value: /app/data_dir
            - name: BASE_URL
              value: https://indexer.finalq.xyz
            - name: REMOTE_AA_ENABLED
              value: "true"
            - name: REMOTE_AA_BASE
              value: https://annas-archive.li
            - name: REMOTE_AA_LANGS
              value: en,es
            - name: REMOTE_AA_EXT
              value: epub
            - name: REMOTE_AA_LIMIT
              value: "25"
            - name: REMOTE_AA_ACCOUNT_ID2
              valueFrom:
                secretKeyRef:
                  name: internal-torznab-indexer-secrets
                  key: REMOTE_AA_ACCOUNT_ID2
