apiVersion: v1
kind: Service
metadata:
  name: internal-torznab-indexer
  namespace: media
  labels:
    app: internal-torznab-indexer
spec:
  type: ClusterIP
  selector:
    app: internal-torznab-indexer
  ports:
    - name: http
      port: 80
      targetPort: 8080
